### ISSUE TITLE
zigzag sampler failed

### ISSUE THREAD

**Issue by chcolapara** [mschauer/ZigZagBoomerang.jl#123]
There is no video tutorial or explanation of how to apply these zigzag sampler algorithms to real data, it is very frustrating because I am trying to apply it to a time series

**Comment by mschauer** [comment]
Why? What are you trying to achieve?

**Comment by chcolapara** [comment]
I try to apply it to a time series and there is no tutorial



[image: Mailtrack]
<https://mailtrack.io?utm_source=gmail&utm_medium=signature&utm_campaign=signaturevirality11&>
Remitente
notificado con
Mailtrack
<https://mailtrack.io?utm_source=gmail&utm_medium=signature&utm_campaign=signaturevirality11&>
15/03/23,
08:42:23

**Comment by chcolapara** [comment]
Can you help me apply it to a series of real data?



[image: Mailtrack]
<https://mailtrack.io?utm_source=gmail&utm_medium=signature&utm_campaign=signaturevirality11&>
Remitente
notificado con
Mailtrack
<https://mailtrack.io?utm_source=gmail&utm_medium=signature&utm_campaign=signaturevirality11&>
15/03/23,
08:45:39

**Comment by mschauer** [comment]
With only the information provided I cannot help and I suggest first learning how to use a more standard tool like Turing: https://turing.ml
